function addFooter(doc){


    const pageCount =
    doc.getNumberOfPages();


    for(
        let i = 1;
        i <= pageCount;
        i++
    ){

        doc.setPage(i);


        doc.setFontSize(9);


        doc.text(

            "Smart Safety Vest Monitoring System",

            20,

            285

        );


        doc.text(

            "Generated by: Admin",

            80,

            285

        );


        doc.text(

            "Page "
            +
            i
            +
            " of "
            +
            pageCount,

            160,

            285

        );


        doc.line(

            20,

            278,

            190,

            278

        );


    }


}

const usersRef =
database.ref("users");


// Current vest assigned worker

const workerId = "zWCufykKMogsDVKJCLZLbkm03RN2";



function generateReport(){


    const workerId = "zWCufykKMogsDVKJCLZLbkm03RN2";


    usersRef.child(workerId)
    .once("value")
    .then((snapshot)=>{


        const worker =
        snapshot.val();



        const { jsPDF } =
        window.jspdf;



        const doc =
        new jsPDF();

        if(logoBase64)
{

doc.addImage(
    logoBase64,
    "PNG",
    150,
    10,
    35,
    35
);

}

doc.setProperties({

    title:
    "Smart Safety Vest Monitoring Report",

    subject:
    "Worker Safety Analysis",

    author:
    "Smart Safety Vest System"

});

       doc.setFontSize(18);

doc.text(
    "Smart Safety Vest Monitoring System",
    20,
    25
);


doc.setFontSize(14);

doc.text(
    "Worker Safety Monitoring Report",
    20,
    38
);


doc.setFontSize(10);

doc.text(
    "Generated: "
    +
    new Date().toLocaleString(),
    20,
    50
);


doc.line(
    20,
    55,
    190,
    55
);



        doc.setFontSize(14);


       doc.autoTable({

    startY: 65,

    head: [

        [
            "Field",
            "Details"
        ]

    ],

    body: [

        [
            "Worker ID",
            workerId
        ],

        [
            "Name",
            worker.name || "-"
        ],

        [
            "Email",
            worker.email || "-"
        ],

        [
            "Role",
            worker.role || "-"
        ],

        [
            "Emergency Contact",
            worker.emergencyContact?.name || "-"
        ],

        [
            "Emergency Phone",
            worker.emergencyContact?.phone || "-"
        ]

    ]

});

// Load sensor history

database.ref("history")
.once("value")
.then((historySnapshot)=>{


    let temperatures = [];
    let humidities = [];
    let gases = [];
    let heartRates = [];
    let fallCount = 0;


    historySnapshot.forEach((item)=>{


        const data = item.val();


        if(data.temperature !== undefined)
            temperatures.push(data.temperature);


        if(data.humidity !== undefined)
            humidities.push(data.humidity);


        if(data.gas !== undefined)
            gases.push(data.gas);


        if(data.heartRate !== undefined)
            heartRates.push(data.heartRate);


        if(data.fall === true)
            fallCount++;


    });



    function average(arr){

        if(arr.length === 0)
            return 0;

        return (
            arr.reduce((a,b)=>a+b,0)
            /
            arr.length
        ).toFixed(2);

    }



    const avgTemperature =
        average(temperatures);


    const maxTemperature =
        temperatures.length
        ?
        Math.max(...temperatures)
        :
        0;


    const avgHumidity =
        average(humidities);


    const avgGas =
        average(gases);


    const maxGas =
        gases.length
        ?
        Math.max(...gases)
        :
        0;


    const avgHeart =
        average(heartRates);


    const maxHeart =
        heartRates.length
        ?
        Math.max(...heartRates)
        :
        0;



    // Statistics Section

    doc.autoTable({

    startY: 150,

    head: [

        [
            "Parameter",
            "Value"
        ]

    ],

    body: [

        [
            "Average Temperature",
            avgTemperature + " °C"
        ],

        [
            "Maximum Temperature",
            maxTemperature + " °C"
        ],

        [
            "Average Humidity",
            avgHumidity + " %"
        ],

        [
            "Average Gas Level",
            avgGas
        ],

        [
            "Maximum Gas Level",
            maxGas
        ],

        [
            "Average Heart Rate",
            avgHeart + " BPM"
        ],

        [
            "Maximum Heart Rate",
            maxHeart + " BPM"
        ],

        [
            "Fall Events",
            fallCount
        ]

    ]

});


let historyRows = [];


historySnapshot.forEach((item)=>{

    const data = item.val();


    historyRows.push([

        data.timestamp
?
new Date(data.timestamp * 1000).toLocaleString()
:
"-",


        data.temperature || "-",


        data.humidity || "-",


        data.gas || "-",


        data.heartRate || "-",


        data.fall
        ?
        "YES"
        :
        "NO"

    ]);

});



doc.addPage();



doc.text(
    "Sensor History",
    20,
    20
);



doc.autoTable({

    startY:30,

    head:[

        [
            "Time",
            "Temp",
            "Humidity",
            "Gas",
            "Heart Rate",
            "Fall"
        ]

    ],


    body: historyRows.slice(0,50)

});

// GPS INFORMATION

database.ref("gps")
.once("value")
.then((gpsSnapshot)=>{


    const gps = gpsSnapshot.val();


    const latitude =
    gps?.latitude || "-";


    const longitude =
    gps?.longitude || "-";


    const mapLink =
    "https://maps.google.com/?q="
    +
    latitude
    +
    ","
    +
    longitude;



    doc.addPage();



    doc.text(
        "GPS Information",
        20,
        20
    );


    doc.autoTable({

        startY:30,


        head:[

            [
                "Field",
                "Details"
            ]

        ],


        body:[

            [
                "Latitude",
                latitude
            ],

            [
                "Longitude",
                longitude
            ],

            [
                "Google Maps",
                mapLink
            ]

        ]


    });




    

   // ALERT SUMMARY

database.ref("alerts")
.once("value")
.then((alertSnapshot)=>{


    let alertRows = [];


    alertSnapshot.forEach((item)=>{


        const alert =
        item.val();



        alertRows.push([


            alert.timestamp
            ?
            new Date(alert.timestamp * 1000)
.toLocaleString()
            :
            "-",


            alert.type || "-",


            alert.message || "-",


            alert.status || "-"


        ]);


    });



    doc.addPage();



    doc.text(

        "Alert Summary",

        20,

        20

    );



    doc.autoTable({

        startY:30,


        head:[

            [

                "Time",

                "Type",

                "Message",

                "Status"

            ]

        ],


        body:

        alertRows.slice(0,50)


    });


// SAFETY STATUS SUMMARY


doc.addPage();


doc.text(
    "Overall Safety Status",
    20,
    25
);



let safetyStatus = "SAFE";

let reasons = [];


// Fall check

if(fallCount > 0)
{

    safetyStatus = "WARNING";

    reasons.push(
        "Fall event detected"
    );

}



// Gas check

if(maxGas > 400)
{

    safetyStatus = "WARNING";

    reasons.push(
        "High gas level detected"
    );

}



// Temperature check

if(maxTemperature > 40)
{

    safetyStatus = "WARNING";

    reasons.push(
        "High temperature detected"
    );

}



doc.autoTable({

    startY:40,


    head:[

        [
            "Status",
            "Details"
        ]

    ],


    body:[

        [
            safetyStatus,
            reasons.length
            ?
            reasons.join(", ")
            :
            "Worker monitoring normal"
        ]

    ]

});



addFooter(doc);

    doc.save(

        workerId
        +
        "_Safety_Report.pdf"

    );


});



});






});

      
});


}