/* ================================================================
   SMART SAFETY VEST — PDF REPORT GENERATOR
   Modern styling only. Original logic & Firebase calls preserved.
   ================================================================ */

const usersRef = database.ref("users");

// Current vest assigned worker
const workerId = "zWCufykKMogsDVKJCLZLbkm03RN2";

/* ---------- PDF Footer Helper ---------- */
function addFooter(doc) {
  const pageCount = doc.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text("Smart Safety Vest Monitoring System", 20, 285);
    doc.text("Generated by: Admin", 80, 285);
    doc.text("Page " + i + " of " + pageCount, 160, 285);
    doc.setDrawColor(226, 232, 240);
    doc.line(20, 278, 190, 278);
  }
}

/* ---------- Report Generator ---------- */
function generateReport() {
  const workerId = "zWCufykKMogsDVKJCLZLbkm03RN2";

  usersRef.child(workerId).once("value").then((snapshot) => {
    const worker = snapshot.val();

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    // Logo
    if (typeof logoBase64 !== "undefined" && logoBase64) {
      doc.addImage(logoBase64, "PNG", 150, 10, 35, 35);
    }

    // Document metadata
    doc.setProperties({
      title:   "Smart Safety Vest Monitoring Report",
      subject: "Worker Safety Analysis",
      author:  "Smart Safety Vest System"
    });

    // Header
    doc.setFontSize(20);
    doc.setTextColor(26, 86, 219);
    doc.text("Smart Safety Vest", 20, 25);

    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Worker Safety Monitoring Report", 20, 35);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text("Generated: " + new Date().toLocaleString(), 20, 45);

    doc.setDrawColor(226, 232, 240);
    doc.line(20, 50, 190, 50);

    // Worker details table
    doc.autoTable({
      startY: 60,
      head: [["Field", "Details"]],
      headStyles: {
        fillColor: [26, 86, 219],
        textColor: 255,
        fontStyle: "bold",
        halign: "left"
      },
      body: [
        ["Worker ID",         workerId],
        ["Name",              worker.name || "-"],
        ["Email",             worker.email || "-"],
        ["Role",              worker.role || "-"],
        ["Emergency Contact", worker.emergencyContact?.name || "-"],
        ["Emergency Phone",   worker.emergencyContact?.phone || "-"]
      ],
      theme: "grid",
      styles: {
        fontSize: 10,
        cellPadding: 3,
        textColor: [30, 41, 59]
      },
      alternateRowStyles: { fillColor: [248, 250, 252] }
    });

    // Sensor history
    database.ref("history").once("value").then((historySnapshot) => {
      let temperatures = [];
      let humidities   = [];
      let gases        = [];
      let heartRates   = [];
      let fallCount    = 0;

      historySnapshot.forEach((item) => {
        const data = item.val();
        if (data.temperature !== undefined) temperatures.push(data.temperature);
        if (data.humidity    !== undefined) humidities.push(data.humidity);
        if (data.gas         !== undefined) gases.push(data.gas);
        if (data.heartRate   !== undefined) heartRates.push(data.heartRate);
        if (data.fall === true)             fallCount++;
      });

      function average(arr) {
        if (arr.length === 0) return "0.00";
        return (arr.reduce((a, b) => a + b, 0) / arr.length).toFixed(2);
      }

      const avgTemperature = average(temperatures);
      const maxTemperature = temperatures.length ? Math.max(...temperatures) : 0;
      const avgHumidity    = average(humidities);
      const avgGas         = average(gases);
      const maxGas         = gases.length        ? Math.max(...gases)        : 0;
      const avgHeart       = average(heartRates);
      const maxHeart       = heartRates.length   ? Math.max(...heartRates)   : 0;

      // Statistics Section
      doc.autoTable({
        startY: doc.lastAutoTable.finalY + 12,
        head: [["Parameter", "Value"]],
        headStyles: {
          fillColor: [26, 86, 219],
          textColor: 255,
          fontStyle: "bold",
          halign: "left"
        },
        body: [
          ["Average Temperature", avgTemperature + " °C"],
          ["Maximum Temperature", maxTemperature + " °C"],
          ["Average Humidity",    avgHumidity + " %"],
          ["Average Gas Level",   avgGas],
          ["Maximum Gas Level",   maxGas],
          ["Average Heart Rate",  avgHeart + " BPM"],
          ["Maximum Heart Rate",  maxHeart + " BPM"],
          ["Fall Events",         fallCount]
        ],
        theme: "grid",
        styles: {
          fontSize: 10,
          cellPadding: 3,
          textColor: [30, 41, 59]
        },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        didParseCell: (data) => {
          if (data.row.index === 1 && maxTemperature > 40) {
            data.cell.styles.textColor = [239, 68, 68];
          }
          if (data.row.index === 4 && maxGas > 400) {
            data.cell.styles.textColor = [239, 68, 68];
          }
        }
      });

      // Sensor history rows
      let historyRows = [];
      historySnapshot.forEach((item) => {
        const data = item.val();
        historyRows.push([
          data.timestamp ? new Date(data.timestamp * 1000).toLocaleString() : "-",
          data.temperature || "-",
          data.humidity    || "-",
          data.gas         || "-",
          data.heartRate   || "-",
          data.fall ? "YES" : "NO"
        ]);
      });

      doc.addPage();
      doc.setFontSize(16);
      doc.setTextColor(26, 86, 219);
      doc.text("Sensor History", 20, 20);

      doc.autoTable({
        startY: 28,
        head: [["Time", "Temp (°C)", "Humidity (%)", "Gas", "Heart Rate", "Fall"]],
        headStyles: {
          fillColor: [26, 86, 219],
          textColor: 255,
          fontStyle: "bold",
          fontSize: 9,
          halign: "center"
        },
        body: historyRows.slice(0, 50),
        theme: "grid",
        styles: {
          fontSize: 8,
          cellPadding: 2,
          textColor: [30, 41, 59],
          halign: "center"
        },
        alternateRowStyles: { fillColor: [248, 250, 252] }
      });

      // GPS Information
      database.ref("gps").once("value").then((gpsSnapshot) => {
        const gps = gpsSnapshot.val();
        const latitude  = gps?.latitude  || "-";
        const longitude = gps?.longitude || "-";
        const mapLink   = (gps?.latitude && gps?.longitude)
          ? "https://maps.google.com/?q=" + latitude + "," + longitude
          : "-";

        doc.addPage();
        doc.setFontSize(16);
        doc.setTextColor(26, 86, 219);
        doc.text("GPS Information", 20, 20);

        doc.autoTable({
          startY: 28,
          head: [["Field", "Details"]],
          headStyles: {
            fillColor: [26, 86, 219],
            textColor: 255,
            fontStyle: "bold",
            halign: "left"
          },
          body: [
            ["Latitude",     latitude],
            ["Longitude",    longitude],
            ["Google Maps",  mapLink]
          ],
          theme: "grid",
          styles: {
            fontSize: 10,
            cellPadding: 3,
            textColor: [30, 41, 59]
          },
          alternateRowStyles: { fillColor: [248, 250, 252] }
        });

        // Alert Summary
        database.ref("alerts").once("value").then((alertSnapshot) => {
          let alertRows = [];

          alertSnapshot.forEach((item) => {
            const alert = item.val();
            alertRows.push([
              alert.timestamp ? new Date(alert.timestamp * 1000).toLocaleString() : "-",
              alert.type    || "-",
              alert.message || "-",
              alert.status  || "-"
            ]);
          });

          doc.addPage();
          doc.setFontSize(16);
          doc.setTextColor(26, 86, 219);
          doc.text("Alert Summary", 20, 20);

          doc.autoTable({
            startY: 28,
            head: [["Time", "Type", "Message", "Status"]],
            headStyles: {
              fillColor: [26, 86, 219],
              textColor: 255,
              fontStyle: "bold",
              fontSize: 9,
              halign: "center"
            },
            body: alertRows.slice(0, 50),
            theme: "grid",
            styles: {
              fontSize: 8,
              cellPadding: 2,
              textColor: [30, 41, 59],
              halign: "center"
            },
            alternateRowStyles: { fillColor: [248, 250, 252] }
          });

          // Overall Safety Status
          doc.addPage();
          doc.setFontSize(16);
          doc.setTextColor(26, 86, 219);
          doc.text("Overall Safety Status", 20, 25);

          let safetyStatus = "SAFE";
          let reasons = [];

          if (fallCount > 0) {
            safetyStatus = "WARNING";
            reasons.push("Fall event detected");
          }
          if (maxGas > 400) {
            safetyStatus = "WARNING";
            reasons.push("High gas level detected");
          }
          if (maxTemperature > 40) {
            safetyStatus = "WARNING";
            reasons.push("High temperature detected");
          }

          const statusColor = (safetyStatus === "SAFE") ? [16, 185, 129] : [239, 68, 68];

          doc.autoTable({
            startY: 35,
            head: [["Status", "Details"]],
            headStyles: {
              fillColor: [26, 86, 219],
              textColor: 255,
              fontStyle: "bold",
              halign: "left"
            },
            body: [
              [
                safetyStatus,
                reasons.length ? reasons.join(", ") : "Worker monitoring normal"
              ]
            ],
            theme: "grid",
            styles: {
              fontSize: 11,
              cellPadding: 5,
              textColor: [30, 41, 59]
            },
            didParseCell: (data) => {
              if (data.column.index === 0 && data.row.index === 0) {
                data.cell.styles.textColor = statusColor;
                data.cell.styles.fontStyle = "bold";
              }
            }
          });

          addFooter(doc);
          doc.save(workerId + "_Safety_Report.pdf");
        });
      });
    });
  });
}
